main = "docker"

[[vendor]]
name = "CLI11"
url = "https://github.com/CLIUtils/CLI11/releases/download/v2.6.2/CLI11.hpp"
sha256 = "227a16fe5f9f8ada80c3c409492475536f597e7bd83a6c26eacc3c8c149a9295"
dest = "root://vendor/"
create_directory = true

[[stages]]
name = "vendor"
description = "Download vendor dependencies"
type = "vendor"

[[stages]]
name = "build"
description = "Build GUI binary"
depends = ["vendor"]
outputs = ["root://bin/predoc-gui"]

[[stages]]
name = "docker"
description = "Build GUI binary via Docker (Linux)"
type = "docker"
outputs = ["root://bin/predoc-gui"]
recipe = "images/linux.Dockerfile"
target = "/build/bin/predoc-gui"
dest = "root://bin/"

[platform.win32.stage.docker]
recipe = "images/win32.Dockerfile"
target = "/build/bin/predoc-gui.exe"
dest = "root://bin/"

[platform.darwin.stage.docker]
recipe = "images/darwin.Dockerfile"
target = "/build/bin/predoc-gui"
dest = "root://bin/"
