main = "hugo-docker"

[[stages]]
name = "cache"
description = "Cache step for ci/cd"

[[stages]]
name = "hugo-binary"
description = "Download Hugo static site generator"
type = "fetch"
fetch-type = "binary"

[[binary]]
name = "hugo"
url = "https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_extended_${VERSION}_${PLATFORM}-${CPU}.tar.gz"
extract = true
version = "0.158.0"
sha256 = "c2a724ac3c8e949fca56dd438b868b2128837754420c20a6e7ae345616c4e625"

[[stages]]
name = "hugo-theme"
description = "Download hugo-book theme"
type = "fetch"
fetch-type = "resource"

[[resource]]
name = "book"
url = "https://github.com/alex-shpak/hugo-book/archive/refs/tags/v${VERSION}.zip"
dest = "root://themes/"
extract = true
create_directory = true
version = "0.14.0"
sha256 = "2332a2b3fb3ddff07ccd6e1eeca49df60401bba54d9617daa6fa5ee71199eb32"

[[stages]]
name = "hugo-build"
description = "Generate static site from content via Hugo"
type = "binary"
binary  = "hugo"
depends = ["hugo-binary", "hugo-theme"]
outputs = ["root://build/index.html"]

[stages.params]
contentDir  = "../content"
themesDir   = "themes"
theme       = "book"
destination = "build"

[[stages]]
name = "hugo-docker"
description = "Generate static site via Docker"
type = "docker"
depends = []
outputs = ["root://build/index.html"]
recipe = "Dockerfile"
target = "/output/build/."
dest = "root://build/"
build_context = "parent"
