main = "docker"
project = "hugo"

[[stages]]
name = "cache"
description = "Cache step for ci/cd"

[[stages]]
name = "hugo-binary"
description = "Download Hugo static site generator"
type = "fetch"
fetch-type = "binary"

[[binary]]
name = "hugo"
url = "https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_extended_${VERSION}_${PLATFORM}-${CPU}.${ARCHEXT}"
extract = true
include = ["hugo"]
version = "0.163.3"
sha256 = "1234302ece1167cef2c252aaa69c89b4f0afc5851f1a30536d693e8e7fc4d1bf"

[platform.win32.binary.hugo]
include = ["hugo.exe"] # not implemented on PowerShell win32
sha256 = "10ce84261773a52aa2dabb4f51b9fe86309592248dbeeef093c6b36b1dacf252"

[[stages]]
name = "hugo-theme"
description = "Download hugo-book theme"
type = "fetch"
fetch-type = "resource"

[[resource]]
name = "book"
url = "https://github.com/alex-shpak/hugo-book/archive/refs/tags/v${VERSION}.zip"
dest = "root://themes/"
extract = true
create_directory = true
version = "0.14.0"
sha256 = "2332a2b3fb3ddff07ccd6e1eeca49df60401bba54d9617daa6fa5ee71199eb32"

[[stages]]
name = "build"
description = "Generate static site from content via Hugo"
type = "binary"
binary  = "hugo"
depends = ["hugo-binary", "hugo-theme"]
outputs = ["root://build/index.html"]

[stages.params]
contentDir  = "../content"
themesDir   = "themes"
theme       = "book"
destination = "build"

[[stages]]
name = "docker"
description = "Generate static site via Docker"
type = "docker"
depends = []
outputs = ["root://build/index.html"]
recipe = "Dockerfile"
target = "/output/build/."
dest = "root://build/"
build_context = "parent"
