main = "docker"

[[stages]]
name = "build-install"
description = "Install local bun dependencies"
type = "binary"
binary = "bun"
args = ["install"]

[[stages]]
name = "build"
description = "Build editor static assets"
type = "binary"
binary = "bun"
depends = ["build-install"]
outputs = ["root://public/"]
args = ["run", "build"]

[[stages]]
name = "docker"
description = "Build editor static assets via Docker"
type = "docker"
outputs = ["root://public/"]
recipe = "Dockerfile"
target = "/output/editor/public/"
dest = "root://public/"
